<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
    <RootNamespace>FeVall.Abac.Abstractions</RootNamespace>
    <AssemblyName>FeVall.Abac.Abstractions</AssemblyName>
  </PropertyGroup>

</Project>
